name = "ODESolvers"
uuid = "8e1f3f4b-b6bd-4884-bf08-d5158d38828a"
authors = ["vishal <95016059+gyanantaran@users.noreply.github.com>"]
version = "0.1.0"

[deps]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
FunctionWrappers = "069b7b12-0de2-55c6-9aab-29f3d0a68a2e"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
DifferentialEquations = "7.16.0"
FunctionWrappers = "1.1.3"
GLMakie = "0.11.2"
LinearAlgebra = "1.11.0"
Plots = "1.40.9"
